=== anointedthedeveloper/XML/bookstore.dtd
<!DOCTYPE bookstore [
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, year)> <!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ATTLIST book id ID #REQUIRED>
]>

=== anointedthedeveloper/XML/books-new.xml
<?xml version="1.0"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd"> <bookstore>
<book id="123">
<title>The Hitchhiker's Guide to the Galaxy</title> <author>Douglas
Adams</author>
<year>1979</year>
</book>
<book id="456">
<title>The Lord of the Rings</title> <author>J.R.R.
Tolkien</author>
<year>1954</year>
</book>
</bookstore>
